### ISSUE TITLE
Adjust tx confirmation flow for Staking Reclaim Escrow

### ISSUE THREAD

**Issue by tjanez** [Zondax/ledger-oasis#108]
Currently, the Ledger screens for the Staking Transfer transaction are ordered as follows:

1. Type
2. Shares
3. Fee
4. Gas limit
5. Address
6. Genesis hash
7. Approve

Please, re-order them to:

1. Type
2. From (rename Address to From to make it more clear that this indicates from which account (validator) to reclaim this delegation)
3. Shares
4. Fee
5. Gas limit
6. Genesis hash
7. Approve

This also more logically follows the Oasis Node CLI's confirmation output, e.g.:

```
You are about to sign the following transaction:
  Method: staking.ReclaimEscrow
  Body:
    From:   oasis1qzn7ztfjlc962yy5yz50zt6tedl60p0aw5n98s0k
    Shares: 300000000000
  Nonce:  0
  Fee:
    Amount: 0.00003 ROSE
    Gas limit: 2000
    (gas price: 0.000000015 ROSE per gas unit)
Other info:
  Genesis document's hash: e2a76b23e48639d7e08c961af77aaf55498c90fd01b70ec996d8f1906869b0d1

You may need to review the transaction on your device if you use a hardware-based signer plugin...
```

**Comment by emmanuelm41** [comment]
This issue is already present in dev branch. It was merged with the [sdk 2.0 upgrade](https://github.com/Zondax/ledger-oasis/issues/110). We could close it.
