### ISSUE TITLE
Add support for Entity signing

### ISSUE THREAD

**Issue by jleni** [ZondaX/ledger-oasis#12]
- Entities are not structured as transactions. The parser should identify them as valid and treat them accordingly.

- More info can be found in the source code:
```
Entity signing (CBOR encoded)
    type Entity struct {
        // ID is the public key identifying the entity.
        ID signature.PublicKey `json:"id"`

        // Nodes is the vector of node identity keys owned by this entity, that
        // will sign the descriptor with the node signing key rather than the
        // entity signing key.
        Nodes []signature.PublicKey `json:"nodes"`

        // AllowEntitySignedNodes is true iff nodes belonging to this entity
        // may be signed with the entity signing key.
        AllowEntitySignedNodes bool `json:"allow_entity_signed_nodes"`
    }
```

The default context prefix in this case is different and it should be matched properly.

**Comment by rllola** [comment]
Do we know the max length for `Nodes []signature.PublicKey `json:"nodes"` ?

**Comment by jleni** [comment]
> Do we know the max length for
> ```
> Nodes []signature.PublicKey `json:"nodes"`
> ```
> ?
@kostko maybe you can comment on this?

**Comment by kostko** [comment]
That is a good question, currently the only limit is and implicit one based on maximum transaction size which is a consensus parameter (by default it is 32kb which would allow roughly 1000 nodes here). We can set it to any reasonably high number (e.g., 128).

**Comment by jleni** [comment]
Thanks! Yes, we won't be able to handle 1000 nodes in a Nano S.
With respect to 128, it should be ok memory-wise, however, almost impossible to navigate in the UI
I am not sure, normal people can have the attention span to verify 128 hexstrings :)
For now, we can set the limit at 128 in `coin.h` so later it can be adjusted if necessary.

**Comment by kostko** [comment]
Oh I see, I didn't think about the UI part :-) Yeah this seems excessive to verify manually. In practice people will not use that many nodes anyway, the most common one will be a single node and then up to 10 or so nodes. So maybe for UI purposes we can set the limit at 16 and adjust if needed.

**Comment by jleni** [comment]
Closing but we are still missing test vectors as described here:
https://github.com/ZondaX/ledger-oasis/issues/24
