### ISSUE TITLE
Add support for registerEntity transaction

### ISSUE THREAD

**Issue by jleni** [ZondaX/ledger-oasis#13]
Depends on #12 

- Add support for `registry.RegisterEntity` transaction

**Some pointers**

https://github.com/oasislabs/oasis-core/blob/master/go/registry/api/api.go#L213-L216

https://github.com/oasislabs/oasis-core/blob/754833e6500840ac1a163b491cd94e7e2441b7c3/go/common/crypto/signature/signature.go#L394

The blob here is a CBOR serialized Entity
https://github.com/oasislabs/oasis-core/blob/754833e6500840ac1a163b491cd94e7e2441b7c3/go/common/crypto/signature/signature.go#L397

**Comment by rllola** [comment]
I have 2 questions : 
- Do we know the max size of the blob `untrusted_raw_value` and is it signed or is it a raw value ?
- Do we know the size of the raw signature ? (https://github.com/oasislabs/oasis-core/blob/754833e6500840ac1a163b491cd94e7e2441b7c3/go/common/crypto/signature/signature.go#L221)

**Comment by jleni** [comment]
we don't know the size of `untrusted_raw_value` but we have some indirect limits. 
By design, we reject anything where overall blob goes beyond these limits:
https://github.com/ZondaX/ledger-oasis-app/blob/79c2c56676bf2e2ec49cb2a5b9493dab9342c42d/src/tx.c#L24-L30

the `untrusted_raw_value` is basically pointer to read-only data that will be parsed. We should not need to allocate memory for that. CBOR will just go through the buffer. You can still calculate some upper bound anyway based on the other limitations that we already have (max number of items, etc.). That would be a good idea anyway.

About the raw signature. It is an Ed25519 signature, so it should be 32 bytes. @kostko Could you confirm this?

**Comment by kostko** [comment]
> About the raw signature. It is an Ed25519 signature, so it should be 64 bytes. @kostko Could you confirm this?

This is correct, Ed25519 signatures are 64 bytes. Public keys are 32 bytes (I got an e-mail where it said 32 bytes above which was incorrect) :-)

**Comment by jleni** [comment]
yes, was typing too fast :). We are using 64. No problem.
