### ISSUE TITLE
Adjust confirmation flow for signing Entity descriptors

### ISSUE THREAD

**Issue by tjanez** [Zondax/ledger-oasis#132]
To more closely match Oasis Node CLI's (future) confirmation output and avoid showing unimportant fields, adjust the confirmation flow to:

1. Initial screen with just Entity in the lower line (similar to the Type initial screen for transactions).
2. ID (use Base64 encoding to match what Oasis Core and what block explorers show).
3. Nodes (if there are any) (use Base64 encoding to match what Oasis Core and what block explorers show).

**Comment by emmanuelm41** [comment]
Closed on #134
