### ISSUE TITLE
Update mainnet hash for Damask upgrade

### ISSUE THREAD

**Issue by matevz** [Zondax/ledger-oasis#175]
Using latest master I noticed the [mainnet genesis hash](https://github.com/Zondax/ledger-oasis/blob/master/app/src/coin.h#L18) is still set to Cobalt. Please update it to match Damask:
`b11b369e0da5bb230b220127f5e7b242d385ef8c6f54906243f30af63c815535`

FYI the current genesis hash is always published here https://docs.oasis.dev/general/oasis-network/network-parameters.

:link: [zboto Link](https://app.clickup.com/t/2nv0g1e)

**Comment by ftheirs** [comment]
Implemented here: https://github.com/Zondax/ledger-oasis/pull/172
