### ISSUE TITLE
Use `cbor_value_validate` to validate cbor canonical order

### ISSUE THREAD

**Issue by rllola** [ZondaX/ledger-oasis#18]
https://intel.github.io/tinycbor/current/a00047.html#ga7636f480757b302845ee38227f15cef1

The latest PR doesn't track of the order of the keys so we need to verify the canonical order.

**Comment by jleni** [comment]
I believe this was fixed here https://github.com/ZondaX/ledger-oasis-app/pull/11/files
@rllola I think it is a good idea to add a quick manual test (new feature we just added) and close this.
