### ISSUE TITLE
small UI fixes

### ISSUE THREAD

**Issue by matevz** [Zondax/ledger-oasis#184]
I noticed two UI annoyances while testing out the latest maintenance-M1-fixes branch b5b7f44e62620c31c1f70e76c11aa7eb3f1d3f3d:
- For ParaTime transactions, the transaction type screen is trimmed on my Nano S (see attachment). Write `(ParaTime)` in the new line and using the upper camel case (`Paratime` → `ParaTime`).
- The `Runtime` screen should be named `ParaTime`. The term `ParaTime` is a user-facing brand while the runtime term is only used internally by developers. It means the same thing though.

![IMG_20230119_100220299](https://user-images.githubusercontent.com/83672/213406498-9c09e721-d2fb-468e-a9d4-8af9ba489928.jpg)
![IMG_20230119_100202016](https://user-images.githubusercontent.com/83672/213406459-f1ff75a4-0d1c-4fff-881f-8b4c03991496.jpg)

:link: [zboto Link](https://app.clickup.com/t/867764gb9)

**Comment by chcmedeiros** [comment]
Ok! I will update those!

**Comment by matevz** [comment]
Confirming this was fixed in ed8a6407361e9f9f473ce9322c5eaf5e8d6d4790.
