### ISSUE TITLE
Allowance transaction doesn't show beneficiary ParaTime name

### ISSUE THREAD

**Issue by matevz** [Zondax/ledger-oasis#190]
When signing Allowance transaction (see https://github.com/oasisprotocol/adrs/blob/main/0014-runtime-signing-tx-with-hardware-wallet.md#changes-to-allowance-transaction section of ADR14), the ParaTime name literal is not shown (e.g. `Emerald`), but its native address is (e.g. `oasis1qr629x0tg9gm5fyhedgs9lw5eh3d8ycdnsxf0run`). For known network/addresses, ParaTime names should be shown instead.

:link: [zboto Link](https://app.clickup.com/t/867781gyr)

**Comment by chcmedeiros** [comment]
I think it's fixed on branch M2-maintenance v2.5.2. Can you test it?

**Comment by matevz** [comment]
I checked out M2-maintenance branch, compiled it and tried to test, but I get
```
$ ./installer_s.sh load
Using test master key b'049bc79d139c70c83a4b19e8922e5ee3e0080bb14a2e8b0752aa42cda90a1463f689b0fa68c1c0246845c2074787b649d0d8a6c0b97d4607065eee3057bdf16b83' 
Using ephemeral key b'04b6de945765209d67badae85ef6316d784dc9f3438f339c81713939d6909cb015653a1d94bc70469934985c2da9d471b2be9581e7ca2376a8c66ce5adb09b05fc'
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/oa/.local/lib/python3.10/site-packages/ledgerblue/loadApp.py", line 267, in <module>
    loader.createApp(code_length, args.apiLevel, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/home/oa/.local/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 346, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/home/oa/.local/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 189, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/home/oa/.local/lib/python3.10/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 5103 (Unknown reason)
```

Did I miss anything?

**Comment by chcmedeiros** [comment]
I need to update the makefile! When it's done, I will get back to you!

**Comment by chcmedeiros** [comment]
Hey @matevz I thought I hadn't updated the Makefile, but actually it had. Maybe this is a problem related to space in the device you are using. Can you uninstall some of your apps and try again?

**Comment by matevz** [comment]
Uninstalling Ethereum app on my Nano S helped.

I tested the allowance behavior again and beneficiary is now to loosely shown. You must always verify the network + address combination in order to show the ParaTime literal. Relying just on the address is not enough, because it's generated from the Runtime ID and a user can make that one up.

**Comment by matevz** [comment]
Confirming Beneficiary address is now correctly shown in today's commits to M2-maintenance branch. Good job.
