### ISSUE TITLE
Maximum context length reached when trying to sign transactions

### ISSUE THREAD

**Issue by david-yan** [ZondaX/ledger-oasis#21]
While testing the cli against the device, I ran into an issue where the maximum context length of 64 would be exceeded. The problem is that the ChainContext is a 32 byte hash of the genesis document, and the prefix of the context, `oasis-core/consensus: tx for chain ` is a 35 length string. 

It seems that we need to either change the way ChainContext is set, or increase the maximum allowed context length.

Reference for setting ChainContext: https://github.com/oasislabs/oasis-core/blob/master/go/genesis/api/api.go#L71

**Comment by jleni** [comment]
Yes, at the moment the limit was set at 64 bytes

https://github.com/ZondaX/ledger-oasis-app/blob/79c2c56676bf2e2ec49cb2a5b9493dab9342c42d/src/lib/coin.h#L36

Very easy to modify. What would be a more appropriate value @david-yan @kostko? For memory reasons, I would avoid a very large number.. 96? 128?

**Comment by david-yan** [comment]
In the current state of the code, the context length is 99 (the length of the chainContext is doubled from the hex encoding). So I think 128 would be a good number.

**Comment by kostko** [comment]
Maximum context length is based on the Ed25519ctx spec and is therefore 255 bytes, see here:
https://github.com/oasislabs/ed25519/blob/master/ed25519.go#L67-L68

**Comment by jleni** [comment]
Ok, I think we had previously discussed something shorter but if you plan to comply with Ed25519 better we modify this and extend to 255
