### ISSUE TITLE
Bump Mainnet chain context

### ISSUE THREAD

**Issue by matevz** [Zondax/ledger-oasis#212]
On November 29 2023, a dump&restore upgrade successfully passed on Oasis Mainnet. Please update the chain context for the Mainnet from `b11b369e0da5bb230b220127f5e7b242d385ef8c6f54906243f30af63c815535` to [`bb3d748def55bdfb797a2ac53ee6ee141e54cd2ab2dc2375f4a0703a178e6e55`](https://docs.oasis.io/node/mainnet/).

**Comment by matevz** [comment]
Attached see the updated Test vector batch.

[runtime_vectors_2023-11-30.zip](https://github.com/Zondax/ledger-oasis/files/13513212/runtime_vectors_2023-11-30.zip)

**Comment by chcmedeiros** [comment]
Just merged the mainnet update.
