### ISSUE TITLE
What relationship (if any) is there between this app and ledger-kusama?

### ISSUE THREAD

**Issue by swedishhat** [Zondax/ledger-oasis#39]
The README.md file instructs users in the Download and Install section to get a pre-built release from `https://github.com/Zondax/ledger-kusama/releases`. Is this a typo or is ledger-oasis built in to Kusama somehow?

**Comment by jleni** [comment]
Hi @swedishhat , there is no relation at all.
We are unifying the instructions so all the app we make are easy to build. This was a mistake while unifying the documentation. Thanks for bringing this up!
It was been fixed already.

**Comment by swedishhat** [comment]
:+1:
