### ISSUE TITLE
Entity metadata support

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-oasis#72]
Reference:
https://zondax.slack.com/archives/CNT9DH6LB/p1607954286218600

Specs:
https://github.com/oasisprotocol/metadata-registry/blob/production/docs/adr/0001-entity-metadata.md#entity-metadata-statements

**Comment by rllola** [comment]
Quick question for oasis dev team :
The context specified in the spec is `oasis-metadata-registry: entity` but it doesn't seem to follow this guide (https://github.com/oasisprotocol/oasis-core/blob/master/docs/crypto.md#contexts) in which it says it start with `oasis-core/`.

Not a blocker, just checking specs consistency.

**Comment by kostko** [comment]
Yes, so that is only for contexts that are part of Oasis Core, the metadata registry is not, so it has its own prefix to make sure it can't slash with anything inside Oasis Core.

**Comment by rllola** [comment]
I have another question regarding the spec. The `serial` field is not specified as optional or required. I am right to assume it is required ? @kostko

**Comment by kostko** [comment]
Ah yes, it is required.

**Comment by rllola** [comment]
I got it to work when it should not. All the tests are passing when I am not enforcing the string constraints for the url, email, keybase and twitter fields.

I will generate extra tests value for those fields just to make sure we are enforcing the constraints.

**Comment by rllola** [comment]
@kostko Is it sure the email max length is 32 ? Looks a bit short.

**Comment by kostko** [comment]
> @kostko Is it sure the email max length is 32 ? Looks a bit short.

Yeah that's correct. There were no issues so far with that maximum length.
