### ISSUE TITLE
Test with extended Ascii character for metadata entity registry name

### ISSUE THREAD

**Issue by rllola** [Zondax/ledger-oasis#79]
Apparently ledger won't print chararcter higher than 127 on the Ascii table (http://www.asciitable.com/). However some name can contain a character which is part of the extended Ascii table (e.g hélène). It will be valid but won't be displayed correctly on the ledger.

Maybe add a test for this special case to verify the display.

**Comment by jleni** [comment]
Test and close

**Comment by jleni** [comment]
In these cases, we have a few options:
- Reject
- Accept and use our `asciify` to convert from utf to representable ascii

**Comment by emmanuelm41** [comment]
I tested the asciify function and the outcome is:

Input --> hélène
Output --> h.l.ne

Is it correct?

**Comment by emmanuelm41** [comment]
I applied that function on the PR #114. We created some Zemu tests. Could you check it @jleni?

**Comment by emmanuelm41** [comment]
@tjanez Do you have an answer for this?

**Comment by tjanez** [comment]
> @tjanez Do you have an answer for this?

Yes.

We would prefer to go with the asciify approach and not reject transactions with non-ascii or extended ascii characters.

But we would like to change the symbol that is used from `.` to `?`. Our reasoning is that it would be:
1. Larger and more visible.
2. More clearly indicate that this is an unknown character.

Would that work for you?

**Comment by emmanuelm41** [comment]
> > @tjanez Do you have an answer for this?
> 
> Yes.
> 
> We would prefer to go with the asciify approach and not reject transactions with non-ascii or extended ascii characters.
> 
> But we would like to change the symbol that is used from `.` to `?`. Our reasoning is that it would be:
> 
> 1. Larger and more visible.
> 2. More clearly indicate that this is an unknown character.
> 
> Would that work for you?

Yes, that works for us! I created the PR.
