### ISSUE TITLE
Update app icons

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-oasis#8]

**Comment by jleni** [comment]
Here are the templates:
https://drive.google.com/file/d/1OOAZWlnLlBSpScPnF5NGJ4AfczB3D591/view
https://drive.google.com/file/d/1FVUWDGYPvLuyiwDFgGYiwfwk7YGsxzJ0/view

You can submit the icons to the repository.

**Comment by Afauvre** [comment]
Sorry but what repo do I submit them to?

**Comment by Afauvre** [comment]
Adding both files here. https://drive.google.com/a/oasislabs.com/file/d/1IFBa1PV9mALtgZ0Q86_69DHmvKpcBpue/view?usp=sharing
https://drive.google.com/a/oasislabs.com/file/d/1fUA2GQEYuwr4bj_Ee9Bph1RsxT7Ff8Tt/view?usp=sharing

**Comment by jleni** [comment]
Icons have been adjusted in https://github.com/Zondax/ledger-oasis-app/commit/3d779ab8797a5c99dec48da76a678742f3ff6742
