### ISSUE TITLE
Question : How to use HD ED25519 keys generated by ledger outside of it ?

### ISSUE THREAD

**Issue by Esya** [Zondax/ledger-oasis#84]
Hi,

I'm currently considering developing a web wallet for Oasis that would have BIP-39/44 support and offer a variety of tools to follow their tokens/handle staking/delegation, but I'd like to support mnemonic phrases and their derived keys as provided by ledger-oasis or bitpie

I've seen that it's more frequent to use secp256k1 as an eliptic curve, is there any specific reason to use ed25519 instead ?  It seems bitpie is also doing the same but currently by using those mnemonics (ledger or bitpie) even using something like [https://github.com/alepop/ed25519-hd-key](https://github.com/alepop/ed25519-hd-key) I'm not falling back to the right pub/private key pairs by using the standard derivation path `m/44'/474'/0'/0/0`

Would you have any pointers here ?  I'd like to offer full ledger support at some point if I do move forward with this project but not being able for users to use their existing wallet & forcing them to generate new keys would be a big downside.

Thanks in advance

**Comment by jleni** [comment]
Specification have changed, so this will not be applicable in future
