### ISSUE TITLE
Support for Governance SubmitProposal

### ISSUE THREAD

**Issue by StreamOfMaya** [Zondax/ledger-oasis#92]
based on: https://docs.google.com/document/d/157PmOBAFBCh9NvogkxFr8dLoNE6QB404-0zqHYoa6z8/edit

**Comment by emmanuelm41** [comment]
This issue is already present in dev branch. It was merged with the [sdk 2.0 upgrade](https://github.com/Zondax/ledger-oasis/issues/110). We could close it.
